from extract import df
import pandas as pd

# Expandir el diccionario 'rating' en dos columnas: 'rating_rate' y 'rating_count'
rating_df = df['rating'].apply(pd.Series)
df['rating_rate'] = rating_df['rate']
df['rating_count'] = rating_df['count']


#eliminamos las columnas irrelevantes
df.drop(['image', 'description', 'rating'], axis=1, inplace=True)

#renombramos las columnas
df.columns = ['id', 'product_title', 'price', 'category', 'rating_rate', 'rating_count']

#testear que los valores no sean incoherentes o negativos
df = df[df['price'] >= 0]
df = df[df['rating_rate'] >= 0]
df = df[df['rating_count'] >= 0]

# Crear columna de valor estimado en stock
df['stock_sold_value'] = df['price'] * df['rating_count']

# Crear columna para categorizar rating_rate
df['rating_rate_level'] = df['rating_rate'].apply(lambda x: 'malo' if x < 2.0 else 'regular' if x < 3 else 'bueno' if x < 4 else 'excelente')

# Remove any null values generated by calculations
df_clean = df.dropna()

# Display the transformed DataFrame
print(df_clean.head())

# Save the transformed DataFrame for the load.py script
df_clean.to_csv("data_output/transformed_data_products.csv", index=False)
